version: 2
updates:
  - package-ecosystem: gradle
    directory: /paper-plugin
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly